apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: abconvert
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: spark-os-website
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-production
      - op: replace
        path: /spec/rules/0/host
        value: spark-os.io
      - op: replace
        path: /spec/rules/1/host
        value: www.spark-os.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: spark-os.io
      - op: replace
        path: /spec/tls/0/hosts/1
        value: www.spark-os.io
      - op: replace
        path: /spec/tls/0/secretName
        value: spark-os-tls
