apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: abconvert
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: spark-os-website
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: spark-os-website
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
      - op: replace
        path: /spec/rules/0/host
        value: spark-os-staging.abconvert.io
      - op: remove
        path: /spec/rules/1
      - op: replace
        path: /spec/tls/0/hosts/0
        value: spark-os-staging.abconvert.io
      - op: remove
        path: /spec/tls/0/hosts/1
      - op: replace
        path: /spec/tls/0/secretName
        value: spark-os-staging-tls
